# Generated by Django 5.2.4 on 2025-07-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("firstapp.customuser",),
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("firstapp.customuser",),
        ),
        migrations.AddField(
            model_name="customuser",
            name="type",
            field=models.CharField(
                choices=[("Seller", "SELLER"), ("Customer", "CUSTOMER")],
                default="Customer",
                max_length=255,
                verbose_name="Type",
            ),
        ),
    ]
