# Generated by Django 5.2.4 on 2025-07-12 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0003_customeradditional_selleradditional"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField()),
                (
                    "phone",
                    models.CharField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number should be 10 digits long and contain only numbers.",
                                regex="^\\d{10}$",
                            )
                        ]
                    ),
                ),
                ("query", models.TextField()),
            ],
        ),
    ]
