# Generated by Django 5.2.4 on 2025-07-13 05:14

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0004_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("Seller", "SELLER"), ("Customer", "CUSTOMER")],
                default=[],
                max_length=15,
                null=True,
            ),
        ),
    ]
